name: identidaddigital
description: Identidad Digital.
version: 1.0.15+43

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Biometric local authentication
  local_auth: ^1.1.6
  # Accelerometer and gyroscope sensors
  sensors: ^2.0.3
  # Picking images from the image library
  image_picker: ^0.8.4
  # Cache network image
  cached_network_image: ^2.2.0
  # QR code rendering
  qr_flutter: ^3.2.0
  # Barcode rendering
  barcode_widget: ^1.5.0
  # Device information
  device_info: ^0.4.2+2
  # HTTP requests
  http: ^0.13.3
  # State management
  provider: ^4.3.2+1
  rxdart: ^0.24.1
  # Local storage
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.0
  # Launch URL
  url_launcher: ^6.0.7
  # Checks for an internet connection
  data_connection_checker: ^0.3.4
  # Firebase
  firebase_core: ^1.21.1
  firebase_database: 7.1.1
  firebase_messaging: 10.0.3
  firebase_analytics: 8.1.2
  # Service locator
  get_it: ^4.0.4
  injectable: ^1.0.4
  # Functional programming
  dartz: ^0.9.1
  # Equality comparisons
  equatable: ^1.2.5
  # Date/number formatting
  intl: ^0.17.0
  # App package information
  package_info: ^0.4.0+17
  # Multipart media types
  mime: ^0.9.6+3
  # Fix exif rotation
  flutter_exif_rotation: ^0.3.2
  flutter_linkify: ^5.0.2
  store_redirect: ^2.0.0
  screen_brightness: ^0.1.3
  flutter_windowmanager: ^0.2.0
  screenshot_callback: 2.0.1
  permission_handler: ^8.1.4
  device_info_plus: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  # mockito: ^4.1.1
  build_runner: any
  injectable_generator: ^1.0.4

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - config/
    - lang/

  fonts:
    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Raleway-Italic.ttf
          style: italic

        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Raleway-Regular.ttf

        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          weight: 100
          style: italic

    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: fonts/HelveticaNeue-Italic.ttf
          style: italic
        - asset: fonts/HelveticaNeue-Light.ttf
          weight: 300
        - asset: fonts/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: fonts/HelveticaNeue-Thin.ttf
          weight: 100
