/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData capture = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData carnet = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData deviceClose = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData face = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData info = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData multipleDevices =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData refresh = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData roble = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData time = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData tree = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fingerprint = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData externalUser = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData internalUser = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData send = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData help = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData password = IconData(0xe812, fontFamily: _kFontFam);
}
